minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade

publicHoistPattern:
  - '*types*'
  - '*eslint*'
  - '*prettier*'
  - '@commitlint/*'

shellEmulator: true

allowBuilds:
  simple-git-hooks: true
