name: autofix.ci

on:
  push:
    branches: [main, develop]
  pull_request_target:
    branches: [main, develop]
    types:
      - opened
      - edited
      - synchronize

jobs:
  autofix:
    uses: yikoyu/workflows/.github/workflows/autofix.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      command: pnpm lint --fix
