name: Publish PR Commit Pkg

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - package.json
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    if: ${{ github.repository == 'owner/repo' }}
    uses: yikoyu/workflows/.github/workflows/publish-pr-commit-pkg.yml@main
    with:
      command: pnpm build:lib
